version: "3.6"
services:
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-provisioning:/etc/grafana/provisioning/
    environment:
      - VIRTUAL_HOST=0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: always

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: greenhouse_db
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    volumes:
      - influxdb-data:/var/lib/influxdb
    restart: always

  mqttbridge:
    build: ./mqtt-bridge
    container_name: mqttbridge
    depends_on:
      - influxdb
    restart: always

volumes:
  grafana-provisioning:
  influxdb-data: