version: "3.6"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      # sudo mkdir -p ./volumes/grafana; chown 472:472 ./volumes/grafana
      - ./volumes/grafana:/var/lib/grafana
    environment:
      - VIRTUAL_HOST=0.0.0.0
      - GF_SERVER_DOMAIN=192.168.1.232
      - GF_AUTH_ANONYMOUS_ENABLED=false
#      - GF_AUTH_ANONYMOUS_ORG_NAME=public
      - GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=local
      - GF_AUTH_PROXY_AUTO_SIGN_UP=false
      - GF_AUTH_PROXY_ENABLED=true

    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: always

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: greenhouse_db
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    volumes:
      - ./volumes/influxdb-data:/var/lib/influxdb
    restart: always

  mqttbridge:
    build: ./mqtt-bridge
    container_name: mqttbridge
    depends_on:
      - influxdb
    restart: always
  nginx-proxy:
    build: ./nginx-proxy
    container_name: nginx-proxy
    ports:
      - "3002:3002"
    depends_on:
      - grafana
    restart: always
