version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    tty: true
    environment:
      - UV_THREADPOOL_SIZE=2
    ports:
      - 80:80
    volumes:
      - ./client/src:/app/src
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: npm run start
    depends_on:
      - mongodb
    ports:
      - 3030:3030
    volumes:
      - ./api/public:/app/public
      - ./api/src:/app/src
    environment:
      - NODE_ENV=production
  mongodb:
    image: mongo:3.6.7
    ports:
      - 27017:27017
    volumes:
       - mongodb-data:/data/db
volumes:
  mongodb-data: