version: "3.6"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - mqtt
    volumes:
      # sudo mkdir -p ./volumes/grafana; chown 472:472 ./volumes/grafana
      - ./volumes/grafana:/var/lib/grafana
    environment:
      - VIRTUAL_HOST=0.0.0.0
      - GF_SERVER_DOMAIN=grafana.juergensen.me
      - GF_SERVER_ROOT_URL=http://grafana.juergensen.me/
      - GF_AUTH_ANONYMOUS_ENABLED=false
#      - GF_AUTH_ANONYMOUS_ORG_NAME=public
      - GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=local
      - GF_AUTH_PROXY_AUTO_SIGN_UP=false
      - GF_AUTH_PROXY_ENABLED=true
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - mqtt
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mvB0
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - mqtt
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_HOST: postgres
    depends_on:
      - postgres
    restart: always

  mqttbridge:
    build: ./mqtt-bridge
    container_name: mqttbridge
    networks:
      - mqtt
    environment:
      MQTT_HOST: 192.168.1.232
      MQTT_USER: ubuntu
      MQTT_PASS: 1234
    depends_on:
      - postgres
      # - mqtt
    restart: always


  nginx-proxy:
    build: ./nginx-proxy
    container_name: nginx-proxy
    networks:
      - mqtt
    ports:
      - "3002:3002"
    depends_on:
      - grafana
    restart: always

networks:
  mqtt:
