version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./local.Dockerfile
    tty: true
    command: npm run serve
    environment:
      - UV_THREADPOOL_SIZE=2
    ports:
      - 8080:8080
    volumes:
      - ./client/src:/app/src
  api:
    build:
      context: ./api
      dockerfile: ./local.Dockerfile
    command: npm run serve
    depends_on:
      - mongodb
    ports:
      - 3030:3030
      - 9999:9999
    volumes:
      - ./api/public:/app/public
      - ./api/src:/app/src
    environment:
      - NODE_ENV=docker
  mongodb:
    image: mongo:3.6.7
    ports:
      - 27017:27017
    volumes:
       - mongodb-data:/data/db
volumes:
  mongodb-data: